# Generated by Django 4.1.7 on 2023-02-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.CharField(max_length=12, verbose_name='БИН/ИИН')),
                ('name_kz', models.CharField(max_length=50, verbose_name='Названи каз')),
                ('name_ru', models.CharField(max_length=50, verbose_name='Названи рус')),
                ('name_en', models.CharField(max_length=50, verbose_name='Названи англ')),
                ('phoneNumber', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Емайл')),
                ('website', models.URLField(verbose_name='Ссылка')),
                ('dBeg', models.DateField(verbose_name='Дата открытие предприятия')),
                ('dEnd', models.DateField(verbose_name='Дата закрытия предприятия')),
                ('cmt_kz', models.CharField(max_length=50, verbose_name='Комментарии (каз)')),
                ('cmt_ru', models.CharField(max_length=50, verbose_name='Комментарии (рус)')),
                ('cmt_en', models.CharField(max_length=50, verbose_name='Комментарии (англ)')),
            ],
        ),
    ]
