# Generated by Django 4.1.7 on 2023-03-16 09:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name_kz', models.CharField(max_length=50, null=True, verbose_name='Наименование организации каз')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Наименование организации рус')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Наименование организации англ')),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bin', models.CharField(max_length=12, verbose_name='БИН/ИИН')),
                ('name_kz', models.CharField(max_length=50, null=True, verbose_name='Названи каз')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Названи рус')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Названи англ')),
                ('phoneNumber', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Емайл')),
                ('website', models.URLField(null=True, verbose_name='Ссылка')),
                ('dBeg', models.DateField(verbose_name='Дата открытие предприятия')),
                ('dEnd', models.DateField(null=True, verbose_name='Дата закрытия предприятия')),
                ('cmt_kz', models.CharField(max_length=50, null=True, verbose_name='Комментарии (каз)')),
                ('cmt_ru', models.CharField(max_length=50, null=True, verbose_name='Комментарии (рус)')),
                ('cmt_en', models.CharField(max_length=50, null=True, verbose_name='Комментарии (англ)')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('instanceNumber', models.CharField(max_length=50, null=True, verbose_name='Инстант')),
                ('dBeg', models.DateField(null=True, verbose_name='Дата установки')),
                ('OS', models.CharField(max_length=50, null=True, verbose_name='Операционная система')),
                ('extMemory', models.CharField(max_length=50, null=True, verbose_name='Номер HD')),
                ('path', models.CharField(max_length=50, null=True, verbose_name='Путь установки')),
                ('iin_superuser', models.CharField(max_length=12, null=True, verbose_name='')),
                ('fio_kz', models.CharField(max_length=50, null=True, verbose_name='ФИО каз.')),
                ('fio_ru', models.CharField(max_length=50, null=True, verbose_name='ФИО рус.')),
                ('email', models.EmailField(max_length=254, verbose_name='Емайл')),
                ('fio_en', models.CharField(max_length=50, null=True, verbose_name='ФИО англ.')),
                ('phoneNumber', models.CharField(max_length=12, verbose_name='')),
                ('cmt_kz', models.CharField(max_length=100, null=True, verbose_name='Коммент каз.')),
                ('cmt_ru', models.CharField(max_length=100, null=True, verbose_name='Коммент рус.')),
                ('cmt_en', models.CharField(max_length=100, null=True, verbose_name='Коммент англ')),
            ],
        ),
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name_kz', models.CharField(max_length=50, null=True, verbose_name='Названи каз')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Названи рус')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Названи англ')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name_kz', models.CharField(max_length=50, null=True, verbose_name='Названи каз')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Названи рус')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Названи англ')),
                ('moduleURL', models.URLField(null=True, verbose_name='Ссылка')),
                ('cmt_kz', models.CharField(max_length=100, null=True, verbose_name='Коммент каз.')),
                ('cmt_ru', models.CharField(max_length=100, null=True, verbose_name='Коммент рус.')),
                ('cmt_en', models.CharField(max_length=100, null=True, verbose_name='Коммент англ')),
            ],
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dtBeg', models.DateField(null=True, verbose_name='Дата оплаты')),
                ('amount', models.CharField(max_length=50, null=True, verbose_name='Сумма оплаты')),
                ('paymentType', models.CharField(max_length=50, null=True, verbose_name='Метод оплаты')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Enterprise.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='WorkMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dtBeg', models.DateField(verbose_name='Дата Начала')),
                ('dtEnd', models.DateField(null=True, verbose_name='Дата окончания')),
                ('response', models.CharField(max_length=50, null=True, verbose_name='Ответ от приложения')),
                ('cmt_kz', models.CharField(max_length=50, null=True, verbose_name='Комментарии (каз)')),
                ('cmt_ru', models.CharField(max_length=50, null=True, verbose_name='Комментарии (рус)')),
                ('cmt_en', models.CharField(max_length=50, null=True, verbose_name='Комментарии (англ)')),
                ('appType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Enterprise.apptype')),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Enterprise.instance')),
                ('massageType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Enterprise.messagetype')),
            ],
        ),
        migrations.CreateModel(
            name='RepaymentModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('monthCount', models.CharField(max_length=50, null=True, verbose_name='Не понятно')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Enterprise.module')),
                ('repayment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Enterprise.repayment')),
            ],
        ),
        migrations.AddField(
            model_name='enterprise',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Enterprise.instance'),
        ),
        migrations.CreateModel(
            name='EnterpriceAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dtEnd', models.DateField(null=True, verbose_name='Дата окончания')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Enterprise.enterprise')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Enterprise.module')),
            ],
        ),
    ]
