# Generated by Django 4.1.7 on 2023-03-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='id',
            field=models.UUIDField(default=1000, primary_key=True, serialize=False),
        ),
    ]
