# Generated by Django 4.1.7 on 2023-02-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kz', models.CharField(max_length=50, verbose_name='Наименование организации каз')),
                ('name_ru', models.CharField(max_length=50, verbose_name='Наименование организации рус')),
                ('name_en', models.CharField(max_length=50, verbose_name='Наименование организации англ')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instanceNumber', models.CharField(max_length=50, verbose_name='Инстант')),
                ('dBeg', models.DateField(verbose_name='Дата установки')),
                ('OS', models.CharField(max_length=50, verbose_name='Операционная система')),
                ('extMemory', models.CharField(max_length=50, verbose_name='Номер HD')),
                ('path', models.CharField(max_length=50, verbose_name='Путь установки')),
                ('iin_superuser', models.CharField(max_length=12, verbose_name='')),
                ('fio_kz', models.CharField(max_length=50, verbose_name='ФИО каз.')),
                ('fio_ru', models.CharField(max_length=50, verbose_name='ФИО рус.')),
                ('fio_en', models.CharField(max_length=50, verbose_name='ФИО англ.')),
                ('phoneNumber', models.CharField(max_length=12, verbose_name='')),
                ('cmt_kz', models.CharField(max_length=100, verbose_name='Коммент каз.')),
                ('cmt_ru', models.CharField(max_length=100, verbose_name='Коммент рус.')),
                ('cmt_en', models.CharField(max_length=100, verbose_name='Коммент англ')),
            ],
        ),
    ]
