# Generated by Django 4.1.7 on 2023-02-28 17:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0002_apptype_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name_kz', models.CharField(max_length=50, null=True, verbose_name='Названи каз')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Названи рус')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Названи англ')),
                ('moduleURL', models.URLField(null=True, verbose_name='Ссылка')),
                ('cmt_kz', models.CharField(max_length=100, null=True, verbose_name='Коммент каз.')),
                ('cmt_ru', models.CharField(max_length=100, null=True, verbose_name='Коммент рус.')),
                ('cmt_en', models.CharField(max_length=100, null=True, verbose_name='Коммент англ')),
            ],
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dtBeg', models.DateField(null=True, verbose_name='Дата оплаты')),
                ('amount', models.CharField(max_length=50, null=True, verbose_name='Сумма оплаты')),
                ('paymentType', models.CharField(max_length=50, null=True, verbose_name='Метод оплаты')),
            ],
        ),
        migrations.AddField(
            model_name='enterprise',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Enterprise.instance'),
        ),
        migrations.AlterField(
            model_name='apptype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apptype',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Наименование организации англ'),
        ),
        migrations.AlterField(
            model_name='apptype',
            name='name_kz',
            field=models.CharField(max_length=50, null=True, verbose_name='Наименование организации каз'),
        ),
        migrations.AlterField(
            model_name='apptype',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Наименование организации рус'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='cmt_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Комментарии (англ)'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='cmt_kz',
            field=models.CharField(max_length=50, null=True, verbose_name='Комментарии (каз)'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='cmt_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Комментарии (рус)'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='dEnd',
            field=models.DateField(null=True, verbose_name='Дата закрытия предприятия'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Емайл'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Названи англ'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='name_kz',
            field=models.CharField(max_length=50, null=True, verbose_name='Названи каз'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Названи рус'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='website',
            field=models.URLField(null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='OS',
            field=models.CharField(max_length=50, null=True, verbose_name='Операционная система'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='cmt_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Коммент англ'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='cmt_kz',
            field=models.CharField(max_length=100, null=True, verbose_name='Коммент каз.'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='cmt_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Коммент рус.'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='dBeg',
            field=models.DateField(null=True, verbose_name='Дата установки'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='extMemory',
            field=models.CharField(max_length=50, null=True, verbose_name='Номер HD'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='fio_en',
            field=models.CharField(max_length=50, null=True, verbose_name='ФИО англ.'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='fio_kz',
            field=models.CharField(max_length=50, null=True, verbose_name='ФИО каз.'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='fio_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='ФИО рус.'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instance',
            name='iin_superuser',
            field=models.CharField(max_length=12, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='instance',
            name='instanceNumber',
            field=models.CharField(max_length=50, null=True, verbose_name='Инстант'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='path',
            field=models.CharField(max_length=50, null=True, verbose_name='Путь установки'),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dtBeg', models.DateField(verbose_name='Дата Начала')),
                ('dtEnd', models.DateField(null=True, verbose_name='Дата окончания')),
                ('response', models.CharField(max_length=50, null=True, verbose_name='Ответ от приложения')),
                ('cmt_kz', models.CharField(max_length=50, null=True, verbose_name='Комментарии (каз)')),
                ('cmt_ru', models.CharField(max_length=50, null=True, verbose_name='Комментарии (рус)')),
                ('cmt_en', models.CharField(max_length=50, null=True, verbose_name='Комментарии (англ)')),
                ('appType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Enterprise.apptype')),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Enterprise.instance')),
            ],
        ),
        migrations.CreateModel(
            name='RepaymentModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('monthCount', models.CharField(max_length=50, null=True, verbose_name='Не понятно')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Enterprise.module')),
                ('repayment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Enterprise.repayment')),
            ],
        ),
        migrations.AddField(
            model_name='repayment',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Enterprise.enterprise'),
        ),
        migrations.CreateModel(
            name='EnterpriceAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dtEnd', models.DateField(null=True, verbose_name='Дата окончания')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Enterprise.enterprise')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Enterprise.module')),
            ],
        ),
    ]
