from django.urls import path
from .views import (InstanceListCreateView,
                    InstanceRetrieveUpdateDestroyView,
                    AppTypeListCreateView,
                    AppTypeRetrieveUpdateDestroyView,
                    EnterpriseListCreateView,
                    EnterpriseRetrieveUpdateDestroyView,
                    WorkListCreateView,
                    WorkRetrieveUpdateDestroyView,
                    ModuleListCreateView,
                    ModuleRetrieveUpdateDestroyView,
                    RepaymentListCreateView,
                    RepaymentRetrieveUpdateDestroyView,
                    EnterpriceAccessListCreateView,
                    EnterpriceAccessRetrieveUpdateDestroyView,
                    RepaymentModuleAccessListCreateView,
                    RepaymentModuleAccessRetrieveUpdateDestroyView)

urlpatterns = [
    path('Instance/', InstanceListCreateView.as_view(), name='enterprise-list'),
    path('Instance/<int:pk>/',InstanceRetrieveUpdateDestroyView.as_view(), name='enterprise-detail'),
    path('AppType/', AppTypeListCreateView.as_view(), name='AppType-list'),
    path('AppType/<int:pk>/',AppTypeRetrieveUpdateDestroyView.as_view(), name='AppType-detail'),
    path('Enterprise/', EnterpriseListCreateView.as_view(), name='enterprise-list'),
    path('Enterprise/<int:pk>/',EnterpriseRetrieveUpdateDestroyView.as_view(), name='enterprise-detail'),
    path('Work/', WorkListCreateView.as_view(), name='Work-list'),
    path('Work/<int:pk>/',WorkRetrieveUpdateDestroyView.as_view(), name='Module-detail'),
    path('Module/', ModuleListCreateView.as_view(), name='Module-list'),
    path('Module/<int:pk>/',ModuleRetrieveUpdateDestroyView.as_view(), name='enterprise-detail'),
    path('Repayment/', RepaymentListCreateView.as_view(), name='Repayment-list'),
    path('Repayment/<int:pk>/',RepaymentRetrieveUpdateDestroyView.as_view(), name='EnterpriceAccess-detail'),
    path('EnterpriceAccess/', EnterpriceAccessListCreateView.as_view(), name='EnterpriceAccess-list'),
    path('EnterpriceAccess/<int:pk>/',EnterpriceAccessRetrieveUpdateDestroyView.as_view(), name='enterprise-detail'),
    path('RepaymentModule/', RepaymentModuleAccessListCreateView.as_view(), name='RepaymentModule-list'),
    path('RepaymentModule/<int:pk>/',RepaymentModuleAccessRetrieveUpdateDestroyView.as_view(), name='RepaymentModule-detail'),
]
